services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: tell-tales-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tell-tales-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
